// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrkoqykpormjkpkeqgjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indya29xeWtwb3Jtamtwa2VxZ2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2OTU2MjUsImV4cCI6MjA0OTI3MTYyNX0.CdgKa7XWjolBDijfBgFmUn9wTTw8aIagDCibj3nkq48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);